export const DOM = {
  pageNav: document.querySelector('.page-nav'),
  main: document.getElementById('main'),
  preloader: document.querySelector('.main--skeleton'),
  buyingSeanceTitle: document.querySelector('.buying__info-title'),
  buyingSeanceStart: document.querySelector('.buying__info-start'),
  buyingSeanceHall: document.querySelector('.buying__info-hall'),
  confStep: document.querySelector('.conf-step'),
  confStepWrapper: document.querySelector('.conf-step__wrapper'),
  priceStandart: document.querySelector('.price-standart'),
  priceVip: document.querySelector('.price-vip'),
  acceptinLink: document.querySelector('.acceptin-link'),
  acceptinButton: document.querySelector('.acceptin-button'),
  ticketTitle: document.querySelector('.ticket__title'),
  ticketChairs: document.querySelector('.ticket__chairs'),
  ticketHall: document.querySelector('.ticket__hall'),
  ticketStart: document.querySelector('.ticket__start'),
  ticketCost: document.querySelector('.ticket__cost'),
  ticketTitle: document.querySelector('.ticket__title'),
  ticketChairs: document.querySelector('.ticket__chairs'),
  ticketHall: document.querySelector('.ticket__hall'),
  ticketStart: document.querySelector('.ticket__start'),
  ticketInfoQr: document.querySelector('.ticket__info-qr'),
}